# An isolated environment for tests and sanity checks on CI

FROM rust:slim-trixie AS builder

# Rust tools
RUN rustup component add rustfmt clippy

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  # Required for tokio and reqwest via `openssl-sys`
  libssl-dev \
  pkg-config \
  # LLVM toolchain for proper LTO support between Rust and C/C++
  clang \
  llvm \
  lld \
  # Valhalla build dependencies
  build-essential \
  cmake \
  libboost-dev \
  liblz4-dev \
  libprotobuf-dev \
  protobuf-compiler \
  zlib1g-dev

# https://doc.rust-lang.org/beta/rustc/linker-plugin-lto.html
ENV CC=clang CXX=clang++ AR=llvm-ar RANLIB=llvm-ranlib
ENV RUSTFLAGS="-Clink-arg=-fuse-ld=lld"

WORKDIR /usr/src/app

# First build a dummy target to cache dependencies in a separate Docker layer
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() { println!("Dummy image called!"); }' > src/main.rs
RUN cargo build

# Now build the real target
COPY src ./src
# Update modified attribute as otherwise cargo won't rebuild it
RUN touch -a -m ./src/main.rs
RUN cargo build

# Check formatting before building to avoid unnecessary rebuilds
RUN cargo fmt --all -- --check

RUN cargo clippy -- -Dwarnings

RUN cargo test
